# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.40.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "aa0d06f0e08a5768fe33205dc18b8be9cf0ecc1c857a267ccd711fc85ba96084"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "05594fa09d14ea0a72996320ab47934d39e14b8a916981b7aa4fdaaf2b5b452f"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "7aee54ef3e15358325f1bd815e8ad400bd51b0613fbb9056695792112dbd0d9e"
    end
  end

  caveats do
    "On first run, macOS may block the binary. To remove the quarantine attribute:"
    "  xattr -d com.apple.quarantine #{staged_path}/lazyworktree"
  end

  # No zap stanza required
end
