# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  version "1.45.0"

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "5c2801db04a388dda96c0446eb810f06cc8da6f78170ff0ecdbb286d3a7afb5d"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "04b7e650b9361094bb07a4d2f921490735e19efd8d623e312574191a717f4498"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "366a5ac3499fb6e4a4daa84ae172404898fb6227e2daca7b46d3f238e5606067"
    end
  end

  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  binary "lazyworktree"

  # No zap stanza required

  caveats <<~EOS
    On first run, macOS may block the binary. To remove the quarantine attribute:
      xattr -d com.apple.quarantine #{staged_path}/lazyworktree
  EOS
end
